DECLARE USER_EXIST INTEGER;
BEGIN SELECT COUNT(*) INTO USER_EXIST FROM dba_users WHERE username='WSO2AM_DB';
IF (USER_EXIST > 0) THEN EXECUTE IMMEDIATE 'DROP USER WSO2AM_DB CASCADE';
END IF;
END;
/
DECLARE USER_EXIST INTEGER;
BEGIN SELECT COUNT(*) INTO USER_EXIST FROM dba_users WHERE username='WSO2AM_SHARED_DB';
IF (USER_EXIST > 0) THEN EXECUTE IMMEDIATE 'DROP USER WSO2AM_SHARED_DB CASCADE';
END IF;
END;
/
CREATE USER WSO2AM_SHARED_DB IDENTIFIED BY wso2carbon;
GRANT CONNECT, RESOURCE, DBA TO WSO2AM_SHARED_DB;
GRANT UNLIMITED TABLESPACE TO WSO2AM_SHARED_DB;
CREATE USER WSO2AM_DB IDENTIFIED BY wso2carbon;
GRANT CONNECT, RESOURCE, DBA TO WSO2AM_DB;
GRANT UNLIMITED TABLESPACE TO WSO2AM_DB;
